
application:
  geminiApiKey:

server:
  port: 8101

logging:
  pattern:
    correlation: "[%X{traceId:-},%X{spanId:-}] "
  level:
    root: INFO
    web: DEBUG
#    sql: DEBUG
    tomcat: DEBUG

spring:
  task:
    scheduling:
      pool:
        size: 5
  application:
    name: integration
  datasource:
    url: jdbc:h2:tcp://localhost/mem:integration
    sql:
      init:
        continue-on-error: true

#eureka:
#  client:
#    enabled: true
#    register-with-eureka: true
#    fetch-registry: true

management:
  endpoint:
    health:
      show-details: ALWAYS
  endpoints:
    enabled-by-default: true
    web:
      exposure:
        include: "*"