#debug: true
logging:
  pattern:
    correlation: "[%X{traceId:-},%X{spanId:-}] "
  level:
    root: INFO
    web: DEBUG
    sql: DEBUG
    tomcat: DEBUG
    org.springframework.security: DEBUG
spring:
  data:
    rest:
      base-path: /api
  jpa:
    hibernate:
#      ddl-auto: create-drop
      ddl-auto: update
  datasource:
    url: jdbc:h2:tcp://localhost/mem:web
    sql:
      init:
        continue-on-error: true
  application:
    name: web
management:
  endpoint:
    health:
      show-details: ALWAYS
  endpoints:
    enabled-by-default: true
    web:
      exposure:
        include: "*"