server:
  port: 8761
logging:
  pattern:
    correlation: "[%X{traceId:-},%X{spanId:-}] "
  level:
    root: INFO
    web: DEBUG
    sql: DEBUG
    tomcat: DEBUG
spring:
  boot:
    admin:
      context-path: "/admin"
  h2:
    console:
      enabled: true
  application:
    name: services
eureka:
  client:
    fetch-registry: false
    register-with-eureka: false
  endpoints:
    enabled-by-default: true
    web:
      exposure:
        include: "*"
